malpiszony = {"Angielski":"Monkey",
            "Japoński":"モンキー",
            "Arabski":"قرد",
            "Azerski":"Meymun",
            "Portugalski":"Macaco",
            "Rosyjski":"Обезьяна",
            "Afrikaans":"Aap",
            "Albański":"Majmun",
            "Amharski":"ዝንጀሮ",
            "Baskijski":"Tximinoa",
            "Bengalski":"বানর",
            "Białoruski":"Малпачка",
            "Birmański":"မျောက်",
            "Bośniaski":"Majmune",
            "Bułgarski":"Маймуна",
            "Cebuański":"Unggoy",
            "Chiński (Tradycyjny)":"猴",
            "Chiński (Uproszczony)":"猴",
            "Czeski":"Opice",
            "Cziczewa":"Nyani",
            "Duński":"Abe",
            "Esperanto":"Simio",
            "Francuski":"Singe",
            "Grecki":"Πίθηκος",
            "Hebrajski":"קוֹף",
            "Hiszpański":"Mono",
            "Igbo":"Enwe",
            "Islandzki":"Apaköttur",
            "Japoński":"猿",
            "Jidysz":"מאַלפּע",
            "Kannada":"ಮಂಕಿ",
            "Koreański":"원숭이",
            "Łaciński":"Simia"}